---
- name: Add route to backend subnet via gateway
  ansible.builtin.command:
    cmd: ip route replace 192.168.20.0/24 via 192.168.10.1
  register: client_route_result
  changed_when: client_route_result.rc == 0